//
//  SFSymbol+All18P1.swift.swift
//
//  Generated Automatically on 6/10/25
//

import Foundation
import Foundation

@available(iOS 18.1, macOS 15.1, tvOS 18.1, watchOS 11.1, visionOS 2.1, *)
public extension SFSymbol {

    static var allSymbols18P1: [SFSymbol] {
        return [
         .boltHouse,
         .boltHouseFill,
         .cableConnectorVideo,
         .carTopRadiowaves2FrontLeftFrontFrontRight,
         .carTopRadiowaves2FrontLeftFrontFrontRightFill,
         .carTopRadiowaves2RearLeftRearRearRight,
         .carTopRadiowaves2RearLeftRearRearRightFill,
         .characterCircleBn,
         .characterCircleFillBn,
         .characterCircleFillGu,
         .characterCircleFillKn,
         .characterCircleFillMl,
         .characterCircleFillMni,
         .characterCircleFillMr,
         .characterCircleFillOr,
         .characterCircleFillPa,
         .characterCircleFillSat,
         .characterCircleFillSi,
         .characterCircleFillTa,
         .characterCircleFillTe,
         .characterCircleGu,
         .characterCircleKn,
         .characterCircleMl,
         .characterCircleMni,
         .characterCircleMr,
         .characterCircleOr,
         .characterCirclePa,
         .characterCircleSat,
         .characterCircleSi,
         .characterCircleTa,
         .characterCircleTe,
         .characterSquareBn,
         .characterSquareFillBn,
         .characterSquareFillGu,
         .characterSquareFillKn,
         .characterSquareFillMl,
         .characterSquareFillMni,
         .characterSquareFillMr,
         .characterSquareFillOr,
         .characterSquareFillPa,
         .characterSquareFillSat,
         .characterSquareFillSi,
         .characterSquareFillTa,
         .characterSquareFillTe,
         .characterSquareGu,
         .characterSquareKn,
         .characterSquareMl,
         .characterSquareMni,
         .characterSquareMr,
         .characterSquareOr,
         .characterSquarePa,
         .characterSquareSat,
         .characterSquareSi,
         .characterSquareTa,
         .characterSquareTe,
         .dotCarTopRadiowaves2RearLeftRearRearRight,
         .dotCarTopRadiowaves2RearLeftRearRearRightFill,
         .envelopeStack,
         .envelopeStackFill,
         .exclamationmarkMessage,
         .exclamationmarkMessageFill,
         .handThumbsdownSlash,
         .handThumbsdownSlashFill,
         .handThumbsupSlash,
         .handThumbsupSlashFill,
         .laurelLeadingLaurelTrailing,
         .memoriesBadgeCheckmark,
         .memoriesBadgeXmark,
         .photoBadgeMagnifyingglass,
         .photoBadgeMagnifyingglassFill,
         .questionmarkMessage,
         .questionmarkMessageFill,
         .rectangleGrid3X1,
         .rectangleGrid3X1Fill,
         .squareAndArrowDownBadgeCheckmark,
         .squareAndArrowDownBadgeCheckmarkFill,
         .squareAndArrowDownBadgeXmark,
         .squareAndArrowDownBadgeXmarkFill,
         .waveformBadgeCheckmark,
         .waveformBadgeXmark,
         .waveformPathEcgMagnifyingglass,
         .waveformPathEcgText,
         .waveformPathEcgTextClipboard,
         .waveformPathEcgTextClipboardFill,
         .waveformPathEcgTextClipboardFillRtl,
         .waveformPathEcgTextClipboardRtl,
         .waveformPathEcgTextPage,
         .waveformPathEcgTextPageFill,
         .waveformPathEcgTextPageFillRtl,
         .waveformPathEcgTextPageRtl,
         .waveformPathEcgTextRtl
      ]
   }
}